// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Cms.Persistence.Models;

public partial class Event
{
    public Guid Id { get; set; }

    public string Description { get; set; } = null!;

    public DateTime EventDate { get; set; }

    public bool IsOneTime { get; set; }

    public bool? IsDayPassed { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public string? DeletedBy { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? IsDeleted { get; set; }
}