// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Cms.Persistence.Models;

public partial class Gender
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;
}