// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Cms.Persistence.Models;

public partial class Menu
{
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;

    public int Order { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool IsDeleted { get; set; }

    public byte[] Timestamp { get; set; } = null!;

    public virtual ICollection<Module> Modules { get; set; } = new List<Module>();
}