// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Cms.Persistence.Models;

public partial class RoleModule
{
    public int RoleId { get; set; }

    public Guid ModuleId { get; set; }

    public bool IsActive { get; set; }

    public virtual Module Module { get; set; } = null!;

    public virtual Role Role { get; set; } = null!;
}